name: SidePVPTournament
main: sapnisdev.sidepvptournament.TournamentPlugin
authors: [ Latvish, Zurius ]
description: 1vs1 pvp Tournament
version: 1.4
api-version: 1.16
commands:
  t:
    aliases: [tournament]
    description: The base command for all tournament commands.