name: SidePVPTournament
main: sapnisdev.sidepvptournament.TournamentPlugin
authors: [ Sapnis ]
description: 1vs1 pvp Tournament
version: 0.1
commands:
  tournament:
    aliases: [t, tourney, st, smarttournament, smartt, stournament, stourney]
    description: The base command for all tournament commands.