#===============================================[ Notes ]================================================#
# name: SidePVPTournament                                                                                  #
# author: Sapnis                                                                                            #
# version: 1.3.7 | build # 41
# PlaceHolders:
#   - t_players_joined
#   - t_max_players
#   - t_till_start
#   - t_arena1_player1
#   - arena1_player2
#   - arena2_player1
#   - arena2_player1
#   - arena2_player2
#========================================================================================================#

configuration:
   prefix: "&4Tournament &8//&a "
   prefix-enabled: true
   tournament-start-delay: 60
   minimum-players-to-start: 2
   maximum-players-allowed: 8
   force-player-clear-inventory: true
   disable-commands-in-tournament: true
   start-when-max-players-reached: false
   disable-join/leave-tournament-message: false
   countdown-values:
   - 120
   - 60
   - 30
   - 15
   - 10
   - 5
   - 3
   - 2
   - 1
   winner-rewards:
      message-enabled: true
      leaderboard-points: true
      reward-command:
   when-fighting:
      ensure-max-health: true
      ensure-max-hunger: true
      ensure-max-saturation: true
      ensure-min-exhaustion: true
      ensure-survival-gamemode: true
      prevent-drop-items: true
   cmd-whitelist:
   - /tournament
   - /st
   - /stournament
   - /smartt
   - /tourney
   - /stourney
   - /msg
   - /r

   limit-plugin-to-specific-worlds: false
   limited-worlds:
   - world

messages:
    no-permission: "&cYou do not have permission to execute this command."
    improper-usage: "&cImproper usage. Proper usage for this command: /t join | vote | setkit | forcestart | leave | start | end | setspawn <arena> <1|2> | setspawn <-spectator|-world>."
    invalid-sender: "&cInvalid sender. You must be a player to perform this command."
    invalid-number: "&cInvalid number. You must enter a positive integer."
    plugin-disabled-in-world: "&cThis plugin is disabled in the world you are currently in."
    severe-error: "&cSevere error. Please contact an administrator."
    no-tournaments-running: "&cThere are currently no tournaments running."
    not-enough-players: "&eThere are not enough players for this tournament to start."
    maximum-players-reached: "&cThe maximum number of allowed joins for this tournament has been reached."
    already-in-tournament: "&cYou are already in the tournament."
    not-in-tournament: "&cYou are currently not in a tournament."
    match-start-broadcast: "&c{initiator} &7and &c{opponent} &7are now fighting."
    match-winner-broadcast: "{winner} has won the match against {loser}!"
    match-idle-broadcast: "&a{initiator}&7 and &a{opponent} &7have both been eliminated for idling."
    match-current-force-end-success: "&aYou have forcefully ended the current match."
    match-specific-force-end-success: "&aYou have forcefully ended the match between &e{initiator} &aand &e{opponent}&a."
    match-force-end-select: "&7Please select which match to end: {matches}"
    match-force-end-select-format: " \n&c#{matchID} &8- &a{initiator} &7vs. &a{opponent}"
    match-force-end-select-separator: "&7, "
    match-force-end-broadcast: "&7The match between &a{initiator}&7 and &a{opponent} &7has been forcefully ended."
    spectator-area-set: "&aYou have successfully set the spectator area."
    arena-invalid-position: "&cInvalid number. You must enter either 1 or 2 for the position."
    arena-set-success: "&7You have successfully set position &a#{position}&7 for the arena: &a{arena}&7."
    require-empty-inventory: "&cYou must empty your inventory and armor contents before joining."
    world-spawn-set: "&aYou have successfully set the world spawn point."
    command-use-denied: "&cYou cannot use this command in the tournament."
    tournament-already-started: "&cThe tournament has already started."
    tournament-areas-not-set: "&cYou must set the world spawn point, spectator area, and arena area(s) first."
    tournament-countdown-broadcast: "&7The tournament will begin in &c{countdown} &7second(s)."
    tournament-joined-success: "&aYou have successfully joined the tournament %SidePVPTournament_players_joined%."
    tournament-joined-broadcast: "&e{username} &7has joined the tournament %SidePVPTournament_players_joined%  ."
    tournament-left-success: "&aYou have successfully left the tournament."
    tournament-left-broadcast: "&e{username} &7has left the tournament."
    tournament-start-success: "&aYou have successfully started the tournament."
    tournament-pre-start-broadcast: "&eA 1v1 tournament is going to begin. Type /tournament join to join the tournament."
    tournament-post-start-broadcast: "&eThe tournament has started!"
    tournament-end-success: "&aYou have successfully ended the tournament."
    tournament-end-broadcast: "&eThe tournament has forcibly been ended."
    tournament-no-winner-broadcast: "&eUnfortunately, no one has won this tournament."
    tournament-winner-broadcast:
      - '&r'
      - '&r'
      - '&c{winner} &7has won the tournament!'
      - '&r'
      - '&r'
    tournament-winner-reward-message: "&dYou have received $10000 for winning this tournament!"
    you-voted: "&7Successfully voted."
    must-be-in: "&cYou need to be in Tournament to vote."
    already-voted: "&cYou have already voted."
    cant-vote: "&cYou cannot vote when game is not started."

kits:
  ARCHER:
    armor: [ ]
    inventory: [ ]
    effects:
      SPEED: 3
    fight-duration: 180
  POTION:
    armor: [ ]
    inventory: [ ]
    effects:
      SPEED: 2
    fight-duration: 180
  GAPPLE:
    armor: [ ]
    inventory: [ ]
    effects:
      SPEED: 2
      INCREASE_DAMAGE: 1
    fight-duration: 180

world-spawn:

spectator:

arenas:

player-logout-data: []